apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytebite-gen-ai
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: bytebite-gen-ai-selector
  template:
    metadata:
      labels:
        app: bytebite-gen-ai-selector
    spec:
      containers:
        - name: gen-ai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
          env:
            - name: LOGOS_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: logos-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai-secret
                  key: openai-api-key
