apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytebite-grocery-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.groceryService.replicaCount }}
  selector:
    matchLabels:
      app: bytebite-grocery-service-selector
  template:
    metadata:
      labels:
        app: bytebite-grocery-service-selector
    spec:
      containers:
        - name: grocery-service
          image: "{{ .Values.groceryService.image.repository }}:{{ .Values.groceryService.image.tag }}"
          imagePullPolicy: {{ .Values.groceryService.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.groceryService.service.targetPort }}
          env:
            - name: GENAI_BASE_URL
              value: "http://genai-service:{{ .Values.genai.service.port }}"
