{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bytebite-prometheus-selector
  ports:
    - port: {{ .Values.monitoring.prometheus.service.port }}
      targetPort: {{ .Values.monitoring.prometheus.service.targetPort }}
      protocol: TCP
  type: {{ .Values.monitoring.prometheus.service.type }}
{{- end }}
