apiVersion: v1
kind: Secret
metadata:
  name: genai-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  logos-key: {{ .Values.genai.logosKey | b64enc | quote }}
  openai-api-key: {{ .Values.genai.openaiApiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user-db-password: {{ .Values.userDb.password | b64enc | quote }}
  grocery-db-password: {{ .Values.groceryDb.password | b64enc | quote }}