ingress:
  enabled: false

client:
  service:
    type: LoadBalancer

monitoring:
  prometheus:
    service:
      type: LoadBalancer
  grafana:
    service:
      type: LoadBalancer

userDb:
  password: bytebite_user_password

groceryDb:
  password: bytebite_grocery_password
